Add 'die' parameter
toastdriven/shell pull request #4
Opened 2017-05-31 19:00 UTC by brandones

I figured this module should have an equivalent for `set -e`.

2017-06-01 06:08 UTC, toastdriven requested changes
I like this a lot. Just need the API changes & I'll be :+1:.

2017-06-01 06:08 UTC, toastdriven commented on docs/tutorial.rst
> +You can have non-zero exit codes propigate as exceptions::
nit: `propigate` -> `propagate`

2017-06-01 06:08 UTC, toastdriven commented on shell.py
> +    def __init__(self, die=False, has_input=False, record_output=True,
Please move `die=False` to the end. Because Python will allow kwargs to be provided by positional args, this would break backward-compatibility if anyone isn't using the kwarg name.

2017-06-01 06:08 UTC, toastdriven commented on shell.py
> +def shell(command, die=False, has_input=False, record_output=True,
Again, please move `die=False` to the end.

2017-06-08 03:17 UTC, toastdriven approved these changes
Thanks!

2017-06-08 03:17 UTC, merged

2018-10-30 13:04 UTC, weakcamel commented
Hello,
The functionality is very useful (actually, it's IMO kind of essential).